Repository kubewarden/docs, pull requests merged in 2024-02, with the labels that each got.

#349 chore: update capability name to fetch OCI image manifest.
  docs/writing-policies/spec/host-capabilities/03-container-registry.md
Labels: kind/chore

#350 Bump docusaurus 3.0.1 to 3.1.1.
  docs/distributing-policies/secure-supply-chain.md
  docs/security/verifying-kubewarden.md
  docs/tasks.md
  docs/writing-policies/go/03-policy-settings.md
  docs/writing-policies/metadata.md
  package.json
  versioned_docs/version-1.10/distributing-policies/secure-supply-chain.md
  versioned_docs/version-1.10/security/verifying-kubewarden.md
  versioned_docs/version-1.10/tasks.md
  versioned_docs/version-1.10/writing-policies/go/03-policy-settings.md
  versioned_docs/version-1.10/writing-policies/metadata.md
  versioned_docs/version-1.7/distributing-policies/secure-supply-chain.md
  versioned_docs/version-1.7/security/verifying-kubewarden.md
  versioned_docs/version-1.7/tasks.md
  versioned_docs/version-1.7/writing-policies/go/03-policy-settings.md
  versioned_docs/version-1.7/writing-policies/index.md
  versioned_docs/version-1.7/writing-policies/metadata.md
  versioned_docs/version-1.8/distributing-policies/secure-supply-chain.md
  versioned_docs/version-1.8/security/verifying-kubewarden.md
  versioned_docs/version-1.8/tasks.md
  versioned_docs/version-1.8/writing-policies/go/03-policy-settings.md
  versioned_docs/version-1.8/writing-policies/metadata.md
  versioned_docs/version-1.9/distributing-policies/secure-supply-chain.md
  versioned_docs/version-1.9/security/verifying-kubewarden.md
  versioned_docs/version-1.9/tasks.md
  versioned_docs/version-1.9/writing-policies/go/03-policy-settings.md
  versioned_docs/version-1.9/writing-policies/metadata.md
  yarn.lock
Labels: area/documentation, kind/chore

#357 Fix frontmatter in refdocs
  docs/reference/spec/01-intro-spec.md
  docs/reference/spec/02-settings.md
  docs/reference/spec/03-validating-policies.md
  docs/reference/spec/04-mutating-policies.md
  docs/reference/spec/05-context-aware-policies.md
  docs/reference/spec/host-capabilities/01-intro-host-capabilities.md
  docs/reference/spec/host-capabilities/02-signature-verifier-policies.md
  docs/reference/spec/host-capabilities/03-container-registry.md
  docs/reference/spec/host-capabilities/04-net.md
  docs/reference/spec/host-capabilities/05-crypto.md
  docs/reference/spec/host-capabilities/06-kubernetes.md
Labels: area/documentation

#355 Update context aware documentation
  docs/reference/spec/05-context-aware-policies.md
Labels: area/documentation

#359 Language review for policy specification 1, 2 and 3.
  docs/reference/spec/01-intro-spec.md
  docs/reference/spec/02-settings.md
  docs/reference/spec/03-validating-policies.md
Labels: area/documentation

#360 Review and update policy specification 4 & 5
  docs/reference/spec/04-mutating-policies.md
  docs/reference/spec/05-context-aware-policies.md
Labels: area/documentation

#363 Refresh language and add link to explanation of OpenTelemetry baggage.
  docs/reference/metrics-reference.md
Labels: area/documentation

#364 Minor refresh of the UI extension howtos
  docs/howtos/ui-extension/01-install.md
  docs/howtos/ui-extension/02-metrics.md
  docs/howtos/ui-extension/03-tracing.md
Labels: area/documentation

#366 Refresh tutorial on policy testing.
  docs/tutorials/testing-policies/02-policy-authors.md
  docs/tutorials/testing-policies/03-cluster-operators.md
  docs/tutorials/testing-policies/index.md
Labels: area/documentation
